name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: bloglite
          POSTGRES_USER: bloguser
          POSTGRES_PASSWORD: blogpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U bloguser -d bloglite"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: bloglite
      DB_USER: bloguser
      DB_PASSWORD: blogpass
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r req.txt
          pip install ruff pytest pytest-cov

      - name: Run Ruff (lint check)
        run: ruff check .

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests with coverage
        run: pytest --cov=. --cov-fail-under=70 --cov-report=term-missing
